# Generated by Django 3.2.25 on 2024-11-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('regulatory_document', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('integration', models.CharField(max_length=200)),
                ('contract_condition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название нарушения')),
                ('example', models.TextField(verbose_name='Пример нарушения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Нарушение',
                'verbose_name_plural': 'Нарушения',
            },
        ),
    ]
